### ISSUE TITLE
Trip cost pro-rated across persons?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#11]
If the the travcost trip file variable is for an exploded person-trip, then has the trip travel cost been pro-rated or otherwise allocated across/to the appropriate persons travelling on that trip?

**Comment by mabcal** [comment]
A good point - for DaySim output, the auto trip costs should be divided per occupant for the HOV2 and HOV3+ trips (which have an average occupancy of about 4).  I will do that in the output for the BCA tool.  Transit fare is per person. 

I'm  not sure how CT-RAMP handles this.

**Comment by jfdman** [comment]
Same for CT-RAMP. Travel costs are skimmed values and not yet prorated by number of persons in travel party. The cost factors should be * 0.62 for shared-2 and * 0.42 for shared 3+. However, CT-RAMP is probably different than DaySim in that auto operating costs are actually not prorated/factored in auto utilities. That is because previous work has shown that factoring auto operating cost by occupancy results in longer trip lengths for shared-ride trips than drive-alone trips, contrary to survey data for urban areas. I suppose with more explicit ridesharing models this should change. But we should keep it in mind if we factor costs in the cost-based benefit calculations and compare the results to the logsum-based calculations.
