### ISSUE TITLE
no race and hispanic demographics daysim household or person fields?

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#13]
at least there isn't any in the trip file variables in bcatest6 spreadsheet.

**Comment by mabcal** [comment]
No - we have never had a client request that variable in the Synthetic population, because then they would need to forecast the racial makeup of neighborhoods in the future, which is a political nightmare.  I think even SANDAG bases that on neighborhood (residence MAZ or TAZ) rather than per household.

**Comment by jfdman** [comment]
I think minority status is tracked in some versions of CT-RAMP (MTC maybe?) but never controlled for in forecasts so somewhat suspect for future years. I would classify such variables as optional segmentation variables that are up to the user to provide.

**Comment by toliwaga** [comment]
Sure - we can support a variable numbers of coc categories.
