### ISSUE TITLE
how much ancillary info is carried into summary/analysis

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#19]
The sandag bca tool carries a very large number of columns into the multiyear processor and final report. This greatly increases its complexity, and reduces its flexibility.

The more parsimonious we are in this area, the easier it will be for the tool to be adapted to different abm data sources. Also it will make it more flexible in terms of experimental modifications to the bca calculations.

My intent is to start by implementing the bare minimum and we can debate the tradeoffs inherent in adding more detailed reporting as we move forward.

Scream if you have a problem with this approach.

**Comment by mabcal** [comment]
I agree.  I will send the revised spreadsheet that Joel distributed....
I think the order this should be done is....
1. Get the very basic version of the Disaggregate trip rule of a half implemented and working.
2. Get the initial version of the Aggregate trip rule of a half working, using the configurable "roster" format.
3. Get the Disaggregate trips to replicate for specific "populations of interest", linking to a person-level file with a series of 0/1 indicators. (This should also add in the auto ownership costs, which need to be based on a household or person-level file, since not all persons make trips so will not all be in the trip file.
4. Get the link-based input working. (Still need to finalize the specs there, but it is relatively siimple)
5. Add in capabilities for logsum-based calculations.  (We need to do some research and recommendations first)

**Comment by jfdman** [comment]
Agree
