### ISSUE TITLE
need full scale dataset to test performance

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#40]
Up until now we have only run this against the trivially small sample database.

We have no idea what the performance will be with a big dataset. It would be nice to find out.

Who is tasked with assembling a full scale dataset for testing?

**Comment by mabcal** [comment]
I will put real test data on the Q drive. I have two scenarios for the trip and link data but only one for the matrix data. Since it's a speed test, for now we can use the same matrix files for both scenarios, so the results will be 0 for that part. If you can factor the Time matrix in the OMX files and create a second set of OMX files we could have a more meaningful test, but would also have to change the demand to not get 0 answers. (I've only been running scenarios in DaySim, not in the Cube part of the system.)

Sent from Outlook Mobile<https://aka.ms/blhgte>



On Thu, Mar 17, 2016 at 4:04 PM -0700, "Jeff Doyle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Up until now we have only run this against the trivially small sample database.

We have no idea what the performance will be with a big dataset. It would be nice to find out.

Who is tasked with assembling a full scale dataset for testing?

-
