### ISSUE TITLE
remove docs and tutorials folder?

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#43]
I think we should remove the docs and tutorials folder.  Maybe we move the tutorial to @toliwaga's account, or maybe branch it off, or move it to devtools, or maybe the doc folder.

**Comment by toliwaga** [comment]
I agree about the tutorials folder. Feel free to toss it. I have a backup. The doc folder can be hidden, as it is mostly a dev aid. 

The docs folder is a work in process but should not be removed. This is the canonical location for the sphinx-generated package docs. 

I will get docs working right when time and resources permit. I stopped working on this project, not because it was finished, but because I was instructed to do so.
