### ISSUE TITLE
taxi mode in daysim

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#8]
Sandag BCA tool maps taxi to auto. I'm looking at daysim TMODEDETP and MODE category codes and wondering how taxi trips are categorized in daysim.

Also wondering whether toll and fare are aggregated into travcost - and whether this is handled the same in CT-RAMP and daysim?

**Comment by mabcal** [comment]
Taxi is not an available mode in DaySim - it ignores taxi, since we don't have any cities where residents use taxi very much (especially now that they're more likely to use Uber or Lyft).  (There might also be double-counting in traffic assignment if taxis are included with light duty commercial vehicles.)

In the default DaySim output, toll, fare, fuel and parking costs are grouped into travcost, but the plan is to list them separately for the BCA tool.

**Comment by jfdman** [comment]
The only model where taxi is differentiated in SANDAG is the airport ground access model. But in that case the output mode for the trip is auto shared-ride 2 or shared-ride 3+ depending upon the party size. So it is not an 'actual' mode in the output data.

**Comment by toliwaga** [comment]
OK - just checking. Sounds like we can ignore it.
