### ISSUE TITLE
daysim purpose category codes

### ISSUE THREAD

**Issue by toliwaga** [RSGInc/bca4abm#9]
Which of the various daysim purpose category codes can appear as tour purposes (pdpurp)?

0 'home'
1 'work'
2 'school'
3 'escort'
4 'pers.bus'
5 'shop'
6 'meal'
7 'social/recreation'
10 'change mode (park and ride)

**Comment by mabcal** [comment]
1 through 7 can be tour purposes.

**Comment by jfdman** [comment]
Tour purposes in SANDAG CT-RAMP models are:
Work (includes trips for work-related)
University
School (can also be differentiated by grade school vs. high school)
Escort
Shop
Other Maintenance
Eat Out
Visiting
Other Discretionary
Work-based (the primary destination of any work-based sub-tour is work-based)

These can map easily to the Daysim purposes except for work-based, if we need to we can map work-based to meal since most work-based sub-tours are for lunch.

**Comment by mabcal** [comment]
I can also create a separate "Work-based" tour purpose with the DaySim output.  That would be the most consistent.
The main effect is that work-based subtours that are for work purpose would get the work tour VOT while other work-based subtours would all get non-work VOT, but if we code them all the same, they all have to get the same VOT.

**Comment by toliwaga** [comment]
I think all we really care is that we can map trip purpose to either 'commute' or 'noncommute'

right now I am using the tour purpose column - but just need to know for each dataset which column and values to use...
