### ISSUE TITLE
non-sequential zones don't quite work

### ISSUE THREAD

**Issue by bstabler** [RSGInc/bca4abm#98]

**Comment by toliwaga** [comment]
the zone_ids branch has a fix for this that works for MACOG, but I haven't done a pull request because I am unsure whether this change will adversely affect existing users that have contiguous 1-based zone ids (the only kind that worked perviously) but also additional data in their skims beyond the highest zone. (e.g. they have 100 zones and 110x110 skim matrices.) In the previous versions, the skims were sliced to the correct size. In the new versions, there are more ways that skims can not align with zones (e.g. gaps in the non-continuous zones) that should be handled with more thought (checking the omx mapping) so added an assert that will break any code where the omx skims sizes don't match the zone count. I am not aware of any users with super-sized omx matrices, but I know this is not unheard of. 

It would be nice if we had some registry of implementations that we could check new versions against to help ensure compatibility, though I realize there are all kinds of logistical and financial issues with creating such a thing.
